apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    description: this is testing purpose pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
