apiVersion: v1
kind: Pod
metadata:
  name: labelspod
  labels:
    env: devlopment
    clasS: pods
spec:
  containers:
    - name: c00
      image: nginx
      command: ["/bin/bash","-c","while true;do echo hello-shaily;slepp 5;done"]
