apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo
spec:
  containers:
  - name: ctr
    image: nginx
    resources:
      limits:
        memory: "800Mi"
      requests:
        memory: "200Mi"
