kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod2                  
spec:                                    
  containers:                      
    - name: ctr2                     
      image: nginx
      ports:
        - containerPort: 80 
