apiVersion: v1
kind: Pod
metadata:
  name: multictrpod
spec:
  containers:
    - name: c001
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-shaily; sleep 5 ; done"]
    - name: c002
      image: nginx
      command: ["/bin/bash", "-c", "while true; do echo Hello-shaily; sleep 5 ; done"]


